config {
  type: "table",
  description: "Dimension des clients",
  columns: {
    id_client: "id du client",
  },
  assertions: {
    uniqueKey: ['id_client'],
    // uniqueKeys: [['user_id'], ['signup_date', 'customer_id']],
    nonNull:['id_client'],
    rowConditions: [
      // 'email like "%@%.%"'
    ]
  }, schema: 'stg'
}

select distinct
    id_client,
    client_nom as nom,
    client_segment as segment,
from ${ ref('stg_commande') }
