config {
  type: "table",
  description: "Fait: Les articles de nos commandes",
  columns: {
    id_commande: "ID de la commande",
    id_ligne: "ID ligne: détail du pannier",
  }
}

select
    id_commande,
    dt_commande,
    id_ligne,
    id_produit,
    montant_vente,
    quantite,
    remise,
    profit,
    (montant_vente / quantite) as prix_unitaire,
    (montant_vente / quantite) * (1 + remise) as prix_unitaire_avant_remise
from ${ ref('stg_commande') }
